(() => {
  let activeId=null, activeStatus='', agents=[], departments=[], lastMessageSignature='', listRequest=0, threadRequest=0, busy=false;
  const el=id=>document.getElementById(id);
  const esc=s=>(s??'').toString().replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  const api=async(path,opts={})=>{const r=await fetch(OMXConnectAdmin.rest+path,{headers:{'Content-Type':'application/json','X-WP-Nonce':OMXConnectAdmin.nonce},cache:'no-store',...opts}); if(!r.ok)throw new Error((await r.json().catch(()=>({message:'Request failed'}))).message||'Request failed');return r.json();};
  const showError=e=>{const node=el('omx-feedback');node.textContent=e.message||String(e);node.hidden=false;node.classList.add('error');setTimeout(()=>node.hidden=true,6500);};
  async function initMeta(){[agents,{departments}]=await Promise.all([api('/admin/agents'),api('/admin/meta')]);el('omx-agent').innerHTML='<option value="0">Unassigned</option>'+agents.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');const opts=departments.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');el('omx-department').innerHTML=opts;el('omx-department-filter').innerHTML='<option value="">All departments</option>'+opts;}
  async function loadStats(){try{const d=await api('/admin/stats');el('omx-total-stat').textContent=d.total;el('omx-open-stat').textContent=d.open_count;el('omx-pending-stat').textContent=d.pending_count;el('omx-unread-stat').textContent=d.unread_count;}catch(e){showError(e);}}
  function statClass(status){return ['open','pending','resolved'].includes(status)?status:'open';}
  async function loadList(){const req=++listRequest,p=new URLSearchParams();if(activeStatus)p.set('status',activeStatus);if(el('omx-search').value.trim())p.set('q',el('omx-search').value.trim());if(el('omx-priority-filter').value)p.set('priority',el('omx-priority-filter').value);if(el('omx-department-filter').value)p.set('department',el('omx-department-filter').value);try{const rows=await api('/admin/conversations'+(p.toString()?'?'+p:''));if(req!==listRequest)return;el('omx-count').textContent=rows.length+' chats';el('omx-conversations').innerHTML=rows.length?rows.map(r=>`<button type="button" class="omx-conv ${Number(r.id)===activeId?'active':''}" data-id="${Number(r.id)}"><span class="omx-avatar">${esc((r.customer_name||'V').trim().charAt(0).toUpperCase())}</span><span class="omx-conv-copy"><span class="omx-conv-title"><strong>${esc(r.customer_name||'Website visitor')}</strong>${Number(r.unread_agent)>0?`<span class="unread">${Number(r.unread_agent)}</span>`:''}</span><span class="omx-preview">${esc((r.last_message||'No messages').slice(0,95))}</span><span class="omx-mini"><span class="status ${statClass(r.status)}">${esc(r.status)}</span><span class="priority ${esc(r.priority)}">${esc(r.priority)}</span>${r.department?`<span class="omx-dept">${esc(r.department)}</span>`:''}</span></span></button>`).join(''):'<div class="omx-empty-list">No conversations found.</div>';document.querySelectorAll('.omx-conv').forEach(b=>b.onclick=()=>openConversation(Number(b.dataset.id),true));}catch(e){showError(e);}}
  const renderAttachment=m=>m.attachment_url?`<a class="omx-attachment" href="${esc(m.attachment_url)}" target="_blank" rel="noopener noreferrer">📎 ${esc(m.attachment_name||'Attachment')}</a>`:'';
  function renderMessages(messages){const signature=messages.map(m=>m.id).join(',');if(signature===lastMessageSignature)return;lastMessageSignature=signature;const area=el('omx-messages');const nearBottom=area.scrollHeight-area.scrollTop-area.clientHeight<90;area.innerHTML=messages.map(m=>`<div class="omx-msg ${esc(m.sender_type)} ${m.message_type==='note'?'note':''}"><div class="omx-msg-author">${m.message_type==='note'?'🔒 Internal note':m.sender_type==='customer'?'Customer':esc(m.sender_name||'Agent')}</div><div class="omx-msg-body">${esc(m.body).replace(/\n/g,'<br>')}</div>${renderAttachment(m)}<small>${esc(m.created_at)}</small></div>`).join('');if(nearBottom||!area.dataset.initialized){area.scrollTop=area.scrollHeight;area.dataset.initialized='1';}}
  async function openConversation(id,manual=false){if(!id)return;const req=++threadRequest;const changed=id!==activeId;activeId=id;if(changed){lastMessageSignature='';el('omx-messages').dataset.initialized='';}try{const d=await api('/admin/conversation/'+id);if(req!==threadRequest||id!==activeId)return;const c=d.conversation;el('omx-empty').hidden=true;el('omx-thread').hidden=false;el('omx-customer-name').textContent=c.customer_name||'Website visitor';el('omx-customer-meta').textContent=[c.customer_email,c.customer_phone].filter(Boolean).join(' • ')||'Website chat';
    // Incoming messages can reopen a resolved chat. Always synchronize live status from the server.
    el('omx-status').value=c.status;el('omx-priority').value=c.priority||'normal';el('omx-department').value=c.department||departments[0]||'';el('omx-agent').value=c.assigned_user||'0';
    // Do not erase tags currently being typed during the background refresh.
    if(document.activeElement!==el('omx-tags')||manual||changed)el('omx-tags').value=c.tags||'';
    renderMessages(d.messages);await loadList();}catch(e){showError(e);}}
  async function update(fields){if(!activeId)return;try{await api('/admin/update',{method:'POST',body:JSON.stringify({conversation_id:activeId,...fields})});await Promise.all([loadList(),loadStats()]);}catch(e){showError(e);await openConversation(activeId);}}
  async function loadCanned(){try{const rows=await api('/admin/canned');el('omx-canned').innerHTML='<option value="">Quick replies…</option>'+rows.map(r=>`<option value="${esc(r.body)}">${esc(r.title)} ${r.shortcut?'('+esc(r.shortcut)+')':''}</option>`).join('');}catch(e){showError(e);}}
  el('omx-send').onclick=async()=>{const body=el('omx-reply').value.trim();if(!activeId||!body||busy)return;busy=true;el('omx-send').disabled=true;try{await api('/admin/reply',{method:'POST',body:JSON.stringify({conversation_id:activeId,body,internal_note:el('omx-note').checked})});el('omx-reply').value='';el('omx-note').checked=false;await openConversation(activeId,true);await loadStats();}catch(e){showError(e);}finally{busy=false;el('omx-send').disabled=false;}};
  el('omx-status').onchange=()=>update({status:el('omx-status').value});el('omx-priority').onchange=()=>update({priority:el('omx-priority').value});el('omx-department').onchange=()=>update({department:el('omx-department').value});el('omx-agent').onchange=()=>update({assigned_user:Number(el('omx-agent').value)});let tagTimer;el('omx-tags').oninput=()=>{clearTimeout(tagTimer);tagTimer=setTimeout(()=>update({tags:el('omx-tags').value}),650);};
  el('omx-canned').onchange=()=>{if(el('omx-canned').value)el('omx-reply').value=el('omx-canned').value;};el('omx-refresh').onclick=()=>{if(activeId)openConversation(activeId,true);else loadList();loadStats();};
  document.querySelectorAll('.omx-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.omx-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeStatus=b.dataset.status;loadList();});
  ['omx-priority-filter','omx-department-filter'].forEach(id=>el(id).onchange=loadList);let searchTimer;el('omx-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadList,350);};
  Promise.all([initMeta(),loadCanned()]).then(()=>{loadList();loadStats();}).catch(showError);
  // Refresh selected thread + its status, but never reset an in-progress reply draft.
  setInterval(()=>{if(document.hidden||busy)return;if(activeId)openConversation(activeId);else loadList();loadStats();},6000);
})();
