(() => {
  const root=document.getElementById('omx-chat-root'); if(!root)return;
  root.style.setProperty('--omx-accent',OMXConnect.accent||'#6C5CE7');
  let pid=localStorage.getItem('omx_connect_pid')||'', open=false;
  root.innerHTML=`<button class="omx-launch" aria-label="Open chat">💬</button><div class="omx-panel"><div class="omx-header"><div><strong>${escapeHtml(OMXConnect.title)}</strong><span>Typically replies shortly</span></div><button class="omx-close">×</button></div><div class="omx-body"><div class="omx-welcome">${escapeHtml(OMXConnect.welcome)}</div><div class="omx-start"><input id="omx-name" placeholder="Your name"><input id="omx-email" type="email" placeholder="Email"><input id="omx-phone" placeholder="Phone (optional)"><button id="omx-start-btn">Start chat</button></div><div class="omx-live" hidden><div class="omx-public-msgs"></div><div class="omx-input"><textarea id="omx-public-text" rows="2" placeholder="Type your message…"></textarea><div class="omx-public-actions"><label class="omx-file-label">📎 Attach<input id="omx-public-file" type="file" accept="image/*,.pdf" hidden></label><button id="omx-public-send">Send</button></div><small id="omx-upload-status"></small></div></div></div></div>`;
  const q=s=>root.querySelector(s);
  const api=async(path,opts={})=>{const r=await fetch(OMXConnect.rest+path,{headers:opts.body instanceof FormData?{}:{'Content-Type':'application/json'},...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Request failed');return d;};
  q('.omx-launch').onclick=()=>{open=!open;q('.omx-panel').classList.toggle('show',open);if(open&&pid)load()}; q('.omx-close').onclick=()=>{open=false;q('.omx-panel').classList.remove('show')};
  async function ensure(){if(pid)return pid;const d=await api('/conversation',{method:'POST',body:JSON.stringify({name:q('#omx-name').value,email:q('#omx-email').value,phone:q('#omx-phone').value})});pid=d.public_id;localStorage.setItem('omx_connect_pid',pid);return pid}
  q('#omx-start-btn').onclick=async()=>{await ensure();showLive();load()}; function showLive(){q('.omx-start').hidden=true;q('.omx-live').hidden=false} if(pid)showLive();
  async function send(){const body=q('#omx-public-text').value.trim();if(!body)return;await ensure();await api('/message',{method:'POST',body:JSON.stringify({public_id:pid,body})});q('#omx-public-text').value='';load()}
  q('#omx-public-send').onclick=send; q('#omx-public-text').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};
  q('#omx-public-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;await ensure();const s=q('#omx-upload-status');s.textContent='Uploading…';try{const fd=new FormData();fd.append('public_id',pid);fd.append('file',f);await api('/upload',{method:'POST',body:fd});s.textContent='Uploaded';e.target.value='';load()}catch(err){s.textContent=err.message}};
  async function load(){if(!pid)return;try{const d=await api('/conversation/'+encodeURIComponent(pid));if(!d.messages)return;showLive();q('.omx-public-msgs').innerHTML=d.messages.map(m=>`<div class="omx-pmsg ${m.sender_type}"><div>${escapeHtml(m.body).replace(/\n/g,'<br>')}</div>${m.attachment_url?`<a href="${escapeHtml(m.attachment_url)}" target="_blank" rel="noopener">📎 ${escapeHtml(m.attachment_name||'Attachment')}</a>`:''}</div>`).join('');q('.omx-public-msgs').scrollTop=q('.omx-public-msgs').scrollHeight}catch(e){}}
  function escapeHtml(s){return (s||'').toString().replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
  setInterval(()=>{if(open&&pid)load()},5000);
})();
